remote_theme: b2a3e8/jekyll-theme-console
#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - C++.md
  - dev.md

style: light # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

footer: 'Y.L or K.M., inherited from <a href="https://www.cnblogs.com/kion/"> here</a>'

style: dark # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

collections:
  rambling:
    output: true
    permalink: /:collection/:name

defaults:
  - 
    values:
      layout: "home"