# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
 - index.md
 - about.md

style: light # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

footer: 'inherited from <a href="https://www.cnblogs.com/kion/"> here</a>'

style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
